name: Deploy docs

on:
  push:
    branches:
      - doc

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci
        working-directory: ./reactjs/05-design-system

      - run: npm run build
        env: 
          TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TURBO_TEAM: douglas-cezaro
        working-directory: ./reactjs/05-design-system

      - name: Deploy storybook
        working-directory: ./reactjs/05-design-system/packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}